// PHQ-9 Scoring TestScript — auto-generated by scripts/generate-test-fixtures.py
// Exercises Library/$evaluate against the boundary/extreme response fixtures.
// Each test block asserts that the computed score, severity band, and
// PROMIS Depression T-Score match the values published in the CQL Library
// (which itself ports the MII PRO upstream FHIRPath lookup table and the
// PROsetta Stone cross-walk).

Instance: phq-9-scoring-test
InstanceOf: TestScript
Usage: #definition
Description: "Exercises PHQ-9 scoring CQL Library against boundary/extreme response fixtures."

* id = "phq-9-scoring-test"
* url = "https://fhir.bih-charite.de/pro-library/TestScript/phq-9-scoring-test"
* version = "0.1.3"
* name = "PHQ9ScoringTest"
* title = "PHQ-9 Scoring Test (boundary/extreme cases)"
* status = #active
* experimental = true
* date = "2026-05-16"
* publisher = "BIH-CEI (provisional steward)"
* description = "Exercises Library/$evaluate against ten QuestionnaireResponse fixtures spanning min, max, and every PHQ-9 severity-band boundary. Each test asserts the CQL Library produces the expected PHQ9TotalScore, PHQ9Severity, and PROMISDepressionTScore."

* extension[+].url = $cqf-knowledgeCapability
* extension[=].valueCode = #shareable

* fixture[+].id = "response-raw-00"
* fixture[=].autocreate = true
* fixture[=].autodelete = true

* fixture[+].id = "response-raw-04"
* fixture[=].autocreate = true
* fixture[=].autodelete = true

* fixture[+].id = "response-raw-05"
* fixture[=].autocreate = true
* fixture[=].autodelete = true

* fixture[+].id = "response-raw-09"
* fixture[=].autocreate = true
* fixture[=].autodelete = true

* fixture[+].id = "response-raw-10"
* fixture[=].autocreate = true
* fixture[=].autodelete = true

* fixture[+].id = "response-raw-14"
* fixture[=].autocreate = true
* fixture[=].autodelete = true

* fixture[+].id = "response-raw-15"
* fixture[=].autocreate = true
* fixture[=].autodelete = true

* fixture[+].id = "response-raw-19"
* fixture[=].autocreate = true
* fixture[=].autodelete = true

* fixture[+].id = "response-raw-20"
* fixture[=].autocreate = true
* fixture[=].autodelete = true

* fixture[+].id = "response-raw-27"
* fixture[=].autocreate = true
* fixture[=].autodelete = true

// raw=0  severity='minimal'  T-Score=37.4
* test[+]
  * name = "raw00_score_severity_tscore"
  * description = "Response with raw sum 0 → PHQ9TotalScore=0, severity='minimal', PROMIS T=37.4"
  * action[+].operation
    * resource = #Library
    * type = $testscript-operation-code#evaluate
    * description = "Invoke Library/phq-9-scoring/$evaluate against the response"
    * encodeRequestUrl = true
    * sourceId = "response-raw-00"
    * params = "/phq-9-scoring/$evaluate?subject=response-raw-00"
  * action[+].assert
    * description = "PHQ9TotalScore == 0"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PHQ9TotalScore').valueInteger = 0"
  * action[+].assert
    * description = "PHQ9Severity == 'minimal'"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PHQ9Severity').valueString = 'minimal'"
  * action[+].assert
    * description = "PROMISDepressionTScore == 37.4"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PROMISDepressionTScore').valueDecimal = 37.4"

// raw=4  severity='minimal'  T-Score=50.5
* test[+]
  * name = "raw04_score_severity_tscore"
  * description = "Response with raw sum 4 → PHQ9TotalScore=4, severity='minimal', PROMIS T=50.5"
  * action[+].operation
    * resource = #Library
    * type = $testscript-operation-code#evaluate
    * description = "Invoke Library/phq-9-scoring/$evaluate against the response"
    * encodeRequestUrl = true
    * sourceId = "response-raw-04"
    * params = "/phq-9-scoring/$evaluate?subject=response-raw-04"
  * action[+].assert
    * description = "PHQ9TotalScore == 4"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PHQ9TotalScore').valueInteger = 4"
  * action[+].assert
    * description = "PHQ9Severity == 'minimal'"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PHQ9Severity').valueString = 'minimal'"
  * action[+].assert
    * description = "PROMISDepressionTScore == 50.5"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PROMISDepressionTScore').valueDecimal = 50.5"

// raw=5  severity='mild'  T-Score=52.5
* test[+]
  * name = "raw05_score_severity_tscore"
  * description = "Response with raw sum 5 → PHQ9TotalScore=5, severity='mild', PROMIS T=52.5"
  * action[+].operation
    * resource = #Library
    * type = $testscript-operation-code#evaluate
    * description = "Invoke Library/phq-9-scoring/$evaluate against the response"
    * encodeRequestUrl = true
    * sourceId = "response-raw-05"
    * params = "/phq-9-scoring/$evaluate?subject=response-raw-05"
  * action[+].assert
    * description = "PHQ9TotalScore == 5"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PHQ9TotalScore').valueInteger = 5"
  * action[+].assert
    * description = "PHQ9Severity == 'mild'"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PHQ9Severity').valueString = 'mild'"
  * action[+].assert
    * description = "PROMISDepressionTScore == 52.5"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PROMISDepressionTScore').valueDecimal = 52.5"

// raw=9  severity='mild'  T-Score=58.6
* test[+]
  * name = "raw09_score_severity_tscore"
  * description = "Response with raw sum 9 → PHQ9TotalScore=9, severity='mild', PROMIS T=58.6"
  * action[+].operation
    * resource = #Library
    * type = $testscript-operation-code#evaluate
    * description = "Invoke Library/phq-9-scoring/$evaluate against the response"
    * encodeRequestUrl = true
    * sourceId = "response-raw-09"
    * params = "/phq-9-scoring/$evaluate?subject=response-raw-09"
  * action[+].assert
    * description = "PHQ9TotalScore == 9"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PHQ9TotalScore').valueInteger = 9"
  * action[+].assert
    * description = "PHQ9Severity == 'mild'"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PHQ9Severity').valueString = 'mild'"
  * action[+].assert
    * description = "PROMISDepressionTScore == 58.6"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PROMISDepressionTScore').valueDecimal = 58.6"

// raw=10  severity='moderate'  T-Score=59.9
* test[+]
  * name = "raw10_score_severity_tscore"
  * description = "Response with raw sum 10 → PHQ9TotalScore=10, severity='moderate', PROMIS T=59.9"
  * action[+].operation
    * resource = #Library
    * type = $testscript-operation-code#evaluate
    * description = "Invoke Library/phq-9-scoring/$evaluate against the response"
    * encodeRequestUrl = true
    * sourceId = "response-raw-10"
    * params = "/phq-9-scoring/$evaluate?subject=response-raw-10"
  * action[+].assert
    * description = "PHQ9TotalScore == 10"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PHQ9TotalScore').valueInteger = 10"
  * action[+].assert
    * description = "PHQ9Severity == 'moderate'"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PHQ9Severity').valueString = 'moderate'"
  * action[+].assert
    * description = "PROMISDepressionTScore == 59.9"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PROMISDepressionTScore').valueDecimal = 59.9"

// raw=14  severity='moderate'  T-Score=64.7
* test[+]
  * name = "raw14_score_severity_tscore"
  * description = "Response with raw sum 14 → PHQ9TotalScore=14, severity='moderate', PROMIS T=64.7"
  * action[+].operation
    * resource = #Library
    * type = $testscript-operation-code#evaluate
    * description = "Invoke Library/phq-9-scoring/$evaluate against the response"
    * encodeRequestUrl = true
    * sourceId = "response-raw-14"
    * params = "/phq-9-scoring/$evaluate?subject=response-raw-14"
  * action[+].assert
    * description = "PHQ9TotalScore == 14"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PHQ9TotalScore').valueInteger = 14"
  * action[+].assert
    * description = "PHQ9Severity == 'moderate'"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PHQ9Severity').valueString = 'moderate'"
  * action[+].assert
    * description = "PROMISDepressionTScore == 64.7"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PROMISDepressionTScore').valueDecimal = 64.7"

// raw=15  severity='moderately severe'  T-Score=65.8
* test[+]
  * name = "raw15_score_severity_tscore"
  * description = "Response with raw sum 15 → PHQ9TotalScore=15, severity='moderately severe', PROMIS T=65.8"
  * action[+].operation
    * resource = #Library
    * type = $testscript-operation-code#evaluate
    * description = "Invoke Library/phq-9-scoring/$evaluate against the response"
    * encodeRequestUrl = true
    * sourceId = "response-raw-15"
    * params = "/phq-9-scoring/$evaluate?subject=response-raw-15"
  * action[+].assert
    * description = "PHQ9TotalScore == 15"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PHQ9TotalScore').valueInteger = 15"
  * action[+].assert
    * description = "PHQ9Severity == 'moderately severe'"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PHQ9Severity').valueString = 'moderately severe'"
  * action[+].assert
    * description = "PROMISDepressionTScore == 65.8"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PROMISDepressionTScore').valueDecimal = 65.8"

// raw=19  severity='moderately severe'  T-Score=70.3
* test[+]
  * name = "raw19_score_severity_tscore"
  * description = "Response with raw sum 19 → PHQ9TotalScore=19, severity='moderately severe', PROMIS T=70.3"
  * action[+].operation
    * resource = #Library
    * type = $testscript-operation-code#evaluate
    * description = "Invoke Library/phq-9-scoring/$evaluate against the response"
    * encodeRequestUrl = true
    * sourceId = "response-raw-19"
    * params = "/phq-9-scoring/$evaluate?subject=response-raw-19"
  * action[+].assert
    * description = "PHQ9TotalScore == 19"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PHQ9TotalScore').valueInteger = 19"
  * action[+].assert
    * description = "PHQ9Severity == 'moderately severe'"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PHQ9Severity').valueString = 'moderately severe'"
  * action[+].assert
    * description = "PROMISDepressionTScore == 70.3"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PROMISDepressionTScore').valueDecimal = 70.3"

// raw=20  severity='severe'  T-Score=71.5
* test[+]
  * name = "raw20_score_severity_tscore"
  * description = "Response with raw sum 20 → PHQ9TotalScore=20, severity='severe', PROMIS T=71.5"
  * action[+].operation
    * resource = #Library
    * type = $testscript-operation-code#evaluate
    * description = "Invoke Library/phq-9-scoring/$evaluate against the response"
    * encodeRequestUrl = true
    * sourceId = "response-raw-20"
    * params = "/phq-9-scoring/$evaluate?subject=response-raw-20"
  * action[+].assert
    * description = "PHQ9TotalScore == 20"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PHQ9TotalScore').valueInteger = 20"
  * action[+].assert
    * description = "PHQ9Severity == 'severe'"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PHQ9Severity').valueString = 'severe'"
  * action[+].assert
    * description = "PROMISDepressionTScore == 71.5"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PROMISDepressionTScore').valueDecimal = 71.5"

// raw=27  severity='severe'  T-Score=82.3
* test[+]
  * name = "raw27_score_severity_tscore"
  * description = "Response with raw sum 27 → PHQ9TotalScore=27, severity='severe', PROMIS T=82.3"
  * action[+].operation
    * resource = #Library
    * type = $testscript-operation-code#evaluate
    * description = "Invoke Library/phq-9-scoring/$evaluate against the response"
    * encodeRequestUrl = true
    * sourceId = "response-raw-27"
    * params = "/phq-9-scoring/$evaluate?subject=response-raw-27"
  * action[+].assert
    * description = "PHQ9TotalScore == 27"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PHQ9TotalScore').valueInteger = 27"
  * action[+].assert
    * description = "PHQ9Severity == 'severe'"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PHQ9Severity').valueString = 'severe'"
  * action[+].assert
    * description = "PROMISDepressionTScore == 82.3"
    * warningOnly = false
    * expression = "Parameters.parameter.where(name='PROMISDepressionTScore').valueDecimal = 82.3"
