#!/usr/bin/env python3
"""
Generate PHQ-9 boundary/extreme test response fixtures + the matching
TestScript FSH that exercises Library/$evaluate against each fixture.

Test design rationale (per Kroenke 2001 cut-points):
  raw=0   minimal             min extreme
  raw=4   minimal             upper edge of minimal band
  raw=5   mild                lower edge of mild band
  raw=9   mild                upper edge of mild band
  raw=10  moderate            lower edge of moderate band
  raw=14  moderate            upper edge of moderate band
  raw=15  moderately severe   lower edge of moderately severe band
  raw=19  moderately severe   upper edge of moderately severe band
  raw=20  severe              lower edge of severe band
  raw=27  severe              max extreme

The pairs (4,5), (9,10), (14,15), (19,20) prove the band-transition
behaviour. (0,27) prove min/max bounds.

PROMIS Depression T-Score expected values come from the PROsetta Stone
cross-walk (same table embedded in input/cql/PHQ9.cql).
"""
import json
import pathlib
import re

# (raw, severity, t_score) — must match the CQL in input/cql/PHQ9.cql
CASES = [
    (0,  "minimal",           37.4),
    (4,  "minimal",           50.5),
    (5,  "mild",              52.5),
    (9,  "mild",              58.6),
    (10, "moderate",          59.9),
    (14, "moderate",          64.7),
    (15, "moderately severe", 65.8),
    (19, "moderately severe", 70.3),
    (20, "severe",            71.5),
    (27, "severe",            82.3),
]

# LOINC codes for the 4-point frequency scale (ordinal 0..3)
LOINC = {
    0: ("LA6568-5", "Not at all"),
    1: ("LA6569-3", "Several days"),
    2: ("LA6570-1", "More than half the days"),
    3: ("LA6571-9", "Nearly every day"),
}

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA_DIR = REPO_ROOT / "input" / "data"
TESTSCRIPT_PATH = REPO_ROOT / "input" / "fsh" / "tests" / "phq-9-scoring-test.fsh"

DATA_DIR.mkdir(parents=True, exist_ok=True)
TESTSCRIPT_PATH.parent.mkdir(parents=True, exist_ok=True)


def distribute(raw: int) -> list[int]:
    """Distribute a target sum across 9 items, each in [0,3]."""
    assert 0 <= raw <= 27
    # Fill items greedily with the highest level until target is consumed
    items = [0] * 9
    remaining = raw
    for i in range(9):
        take = min(3, remaining)
        items[i] = take
        remaining -= take
    assert sum(items) == raw, f"distribution {items} sums to {sum(items)}, expected {raw}"
    return items


def make_response(raw: int) -> dict:
    """Build a QuestionnaireResponse with Q1-Q9 answered to sum to `raw`."""
    levels = distribute(raw)
    items = []
    for i, level in enumerate(levels, start=1):
        code, display = LOINC[level]
        items.append({
            "linkId": f"phq-phq9-q{i:02d}",
            "answer": [{
                "valueCoding": {
                    "system": "http://loinc.org",
                    "code": code,
                    "display": display,
                }
            }]
        })
    return {
        "resourceType": "QuestionnaireResponse",
        "id": f"phq-9-response-raw-{raw:02d}",
        "questionnaire": "https://fhir.bih-charite.de/pro-library/Questionnaire/phq-9|0.1.1",
        "status": "completed",
        "subject": {"display": "Test fixture — anonymous"},
        "authored": "2026-05-16T10:30:00Z",
        "item": items,
        "_comment_purpose": f"Boundary/extreme test fixture — raw=={raw}",
    }


def write_fixtures():
    for raw, *_ in CASES:
        path = DATA_DIR / f"phq-9-response-raw-{raw:02d}.json"
        with path.open("w") as f:
            json.dump(make_response(raw), f, indent=2, ensure_ascii=False)
        print(f"wrote {path.relative_to(REPO_ROOT)}")


def write_testscript():
    lines = [
        "// PHQ-9 Scoring TestScript — auto-generated by scripts/generate-test-fixtures.py",
        "// Exercises Library/$evaluate against the boundary/extreme response fixtures.",
        "// Each test block asserts that the computed score, severity band, and",
        "// PROMIS Depression T-Score match the values published in the CQL Library",
        "// (which itself ports the MII PRO upstream FHIRPath lookup table and the",
        "// PROsetta Stone cross-walk).",
        "",
        "Instance: phq-9-scoring-test",
        "InstanceOf: TestScript",
        "Usage: #definition",
        'Description: "Exercises PHQ-9 scoring CQL Library against boundary/extreme response fixtures."',
        "",
        '* id = "phq-9-scoring-test"',
        '* url = "https://fhir.bih-charite.de/pro-library/TestScript/phq-9-scoring-test"',
        '* version = "0.1.1"',
        '* name = "PHQ9ScoringTest"',
        '* title = "PHQ-9 Scoring Test (boundary/extreme cases)"',
        "* status = #active",
        "* experimental = true",
        '* date = "2026-05-16"',
        '* publisher = "BIH-CEI (provisional steward)"',
        '* description = "Exercises Library/$evaluate against ten QuestionnaireResponse fixtures spanning min, max, and every PHQ-9 severity-band boundary. Each test asserts the CQL Library produces the expected PHQ9TotalScore, PHQ9Severity, and PROMISDepressionTScore."',
        "",
        "* extension[+].url = $cqf-knowledgeCapability",
        "* extension[=].valueCode = #shareable",
        "",
    ]

    # Fixtures
    for raw, _, _ in CASES:
        fixture_id = f"response-raw-{raw:02d}"
        lines.append(f"* fixture[+].id = \"{fixture_id}\"")
        lines.append("* fixture[=].autocreate = true")
        lines.append("* fixture[=].autodelete = true")
        # No resource reference — fixtures are loaded externally by the test runner
        # from input/data/phq-9-response-raw-XX.json
        lines.append("")

    # Test blocks
    for raw, severity, tscore in CASES:
        fixture_id = f"response-raw-{raw:02d}"
        lines.extend([
            f"// raw={raw}  severity='{severity}'  T-Score={tscore}",
            "* test[+]",
            f'  * name = "raw{raw:02d}_score_severity_tscore"',
            f'  * description = "Response with raw sum {raw} → PHQ9TotalScore={raw}, severity=\'{severity}\', PROMIS T={tscore}"',
            "  * action[+].operation",
            "    * resource = #Library",
            "    * type = $testscript-operation-code#evaluate",
            "    * description = \"Invoke Library/phq-9-scoring/$evaluate against the response\"",
            "    * encodeRequestUrl = true",
            f"    * sourceId = \"{fixture_id}\"",
            f"    * params = \"/phq-9-scoring/$evaluate?subject={fixture_id}\"",
            "  * action[+].assert",
            f"    * description = \"PHQ9TotalScore == {raw}\"",
            "    * warningOnly = false",
            f"    * expression = \"Parameters.parameter.where(name='PHQ9TotalScore').valueInteger = {raw}\"",
            "  * action[+].assert",
            f"    * description = \"PHQ9Severity == '{severity}'\"",
            "    * warningOnly = false",
            f"    * expression = \"Parameters.parameter.where(name='PHQ9Severity').valueString = '{severity}'\"",
            "  * action[+].assert",
            f"    * description = \"PROMISDepressionTScore == {tscore}\"",
            "    * warningOnly = false",
            f"    * expression = \"Parameters.parameter.where(name='PROMISDepressionTScore').valueDecimal = {tscore}\"",
            "",
        ])

    with TESTSCRIPT_PATH.open("w") as f:
        f.write("\n".join(lines))
    print(f"wrote {TESTSCRIPT_PATH.relative_to(REPO_ROOT)}")


# Alias for the TestScript operation-code CodeSystem
ALIAS_TESTSCRIPT_OP = "Alias: $testscript-operation-code = http://terminology.hl7.org/CodeSystem/testscript-operation-codes"


if __name__ == "__main__":
    write_fixtures()
    write_testscript()
    print()
    print("Add this alias to input/fsh/aliases.fsh if not already present:")
    print(f"  {ALIAS_TESTSCRIPT_OP}")
